# Minimal local-dev values for Polaris.
dashboard:
  enable: true

webhook:
  enable: true

config:
  checks:
    runAsPrivileged: danger
    privilegeEscalationAllowed: danger
    hostNetworkSet: danger
    tagNotSpecified: danger
    cpuRequestsMissing: warning
    memoryRequestsMissing: warning
