apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: keycloak
deploy:
  helm:
    releases:
      - name: keycloak
        repo: https://charts.bitnami.com/bitnami
        remoteChart: keycloak
        version: 9.6.2
        namespace: keycloak
        createNamespace: true
        valuesFiles: [values.yaml]