auth:
  adminUser: admin
  adminPassword: adminpassword
          
service:
  type: ClusterIP


ingress:
  enabled: true
  ingressClassName: traefik    
  hostname: keycloak.127.0.0.1.nip.io
  path: /
  pathType: Prefix
  tls: false


extraStartupProbe:
  httpGet:
    path: /realms/master
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 30
