kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: platform-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 32080
        hostPort: 80
      - containerPort: 32443
        hostPort: 443
  - role: worker
    image: kindest/node:v1.34.0
  - role: worker
    image: kindest/node:v1.34.0
